### ISSUE TITLE
User streams API の filter 機能を使って検索できるようにする

### ISSUE THREAD

**Issue by ryota-ka** [ryota-ka/twterm#158]

**Comment by ymyzk** [comment]
REST API の search と User Streams API の filter は前者はクエリに演算子使えるけど, 後者はあまり複雑なことができないので, 単純に置換していいものではないかも.

* https://dev.twitter.com/rest/reference/get/search/tweets
* https://dev.twitter.com/streaming/reference/post/statuses/filter
* https://dev.twitter.com/streaming/overview/request-parameters#track

**Comment by ryota-ka** [comment]
と思ったので実は enhancement じゃなくて feature になってたりする。

**Comment by ryota-ka** [comment]
User streams API has been deprecated.
