### ISSUE TITLE
ユーザーのアイコンを表示する

### ISSUE THREAD

**Issue by lotz84** [ryota-ka/twterm#161]
ユーザーを名前よりアイコンで見分けてるのでどうしても辛いです。
普通に表示するのは難しそうだから画像から代表的な色だけ取ってきてユーザーのイメージカラーの表示とかできませんか

**Comment by ryota-ka** [comment]
Curses を使っている以上、ANSI カラーの8色しか使えないので、なかなか厳しそうな気がします……

**Comment by lotz84** [comment]
８色だと微妙かな…

**Comment by lotz84** [comment]
せめて iTerm2 だけでも
http://www.iterm2.com/images.html

**Comment by ryota-ka** [comment]
@lotz84  出，出〜〜〜〜〜〜ｗｗｗｗｗｗｗ 極度環境依存実装要求奴〜〜〜〜〜〜〜〜〜〜〜〜ｗｗｗｗｗｗｗｗｗｗｗｗｗｗｗｗｗｗｗ

**Comment by lotz84** [comment]
![](http://tiqav.com/5KL.jpg)
