### ISSUE TITLE
自分自身のユーザータブの表示

### ISSUE THREAD

**Issue by ymyzk** [ryota-ka/twterm#231]
自分自身のユーザータブの表示の細部を改善してほしい.
具体的には `[not following]` 表示や `Follow this user` の表示は不要.

さらに自分自身のユーザータブから bio とかが簡単に編集できると良さそう.

**Comment by ryota-ka** [comment]
あれ，自分自身だと `[your account]` って出ません？

**Comment by ymyzk** [comment]
こちらでは確認できてません. 3e987d7 で確認.

**Comment by ryota-ka** [comment]
うーむ，こんな具合で表示されるようにしたつもりなのですが．
![screenshot](https://gyazo.com/3d89e3cb5986ecbea10ad6636622b6fc.png)

**Comment by ryota-ka** [comment]
#236 で直った！はず！

**Comment by ymyzk** [comment]
82cdcc4db9f1c4bd5b20d0413d0c91c13f28725d を使っていますが, 再認証後動作することを確認しまsita.
