### ISSUE TITLE
AND検索と検索ワードの削除

### ISSUE THREAD

**Issue by akawshi** [ryota-ka/twterm#235]
AND検索に対応してほしい。あと, 検索に入れたワードを削除できないので少し不便

**Comment by ryota-ka** [comment]
これって `/` キーでのタブ内検索のことでしょうか？

**Comment by akawshi** [comment]
タブ内検索ですが, AND検索は対応してましたね…。失礼しました。

**Comment by ryota-ka** [comment]
これ今更ですが， `q` キーで検索解除できませんか……？(そういう意味ではないでしょうか……)

**Comment by akawshi** [comment]
filter mode の解除は q キーで解除できるんですけど, filter mode で入力中のデータを途中で修正できたらと思ったのです。

**Comment by ryota-ka** [comment]
943bf0e29a18338546332ac7af38e382d36adf1b で，`<C-c>` ないし `Esc` で入力をキャンセルできるようにしたつもりなのですが，正常に動作していませんか？
(version 1.1.0 以降で有効になっていると思います．)

**Comment by ryota-ka** [comment]
無事に動いていたようでよかった :clap: :clap: 
https://twitter.com/akawshi/status/670241509850001408
