### ISSUE TITLE
required_ruby_version の矛盾

### ISSUE THREAD

**Issue by ymyzk** [ryota-ka/twterm#264]
必要な Ruby のバージョンについて, `twterm.gemspec` では [2.0.0 以上となっている](https://github.com/ryota-ka/twterm/blob/v1.2.2/twterm.gemspec#L19) が,
[README.md](https://github.com/ryota-ka/twterm/blob/v1.2.2/README.md) では 2.1 以上となっていて指定が矛盾している.

**Comment by ryota-ka** [comment]
わかる (あとから 2.0.0 でも動くようにしたときに変えるの忘れたのだろうなぁ)

**Comment by ymyzk** [comment]
なるほど. 逆かと思った. `twterm.gemspec` の方が正しいなら, インストールできるのに動かないとかなさそうで良い.

**Comment by ryota-ka** [comment]
Ruby 2.0 はもう EOL なので，サポート切る方針で進めます．

**Comment by ryota-ka** [comment]
fixed in 45632dd
