### ISSUE TITLE
Cannot enter diacritics / chars with accents - Unicode codes being entered instead

### ISSUE THREAD

**Issue by dkvasnicka** [ryota-ka/twterm#386]
I'm trying to compose a tweet in Czech using non-ASCII characters with diacritical marks. When I try to enter the word "česky" I get:

```
Compose new Tweet

> \U+FFC4esky
```

Happens on Mac, tested in iTerm2 and Terminal.

**Comment by ryota-ka** [comment]
Hmm, are you using Ruby compiled with Readline?
(You can install it with Homebrew.)

Many Japanese users (you may know we use lots of non-ASCII characters!) have told me that they couldn't type Japanese characters, but such problems have been usually solved by installing Readline.

**Comment by dkvasnicka** [comment]
Solved by installing Ruby 2.5 via RVM. Thanks for the hint.

**Comment by ryota-ka** [comment]
Happy to hear that :)
