### ISSUE TITLE
nix installation fails

### ISSUE THREAD

**Issue by mmngreco** [ryota-ka/twterm#443]
Hi there,

I was trying to install `twterm` using nix as recommended but I could't make it works (I'm not familiarized with nix).

```bash
$ nix-channel --add https://github.com/ryota-ka/twterm/archive/master.tar.gz
$ nix-env -iA twterm
error: attribute 'twterm' in selection path 'twterm' not found
```

**Comment by ryota-ka** [comment]
Hi @mmngreco, could you try `$ nix-channel --update` before `nix-env -i`?

**Comment by mmngreco** [comment]
Hi, sorry for delay:

Doesn't seems to work neither. Here's my log:


```bash
~ (10:44|0s) $ nix-channel --update
these derivations will be built:
  /nix/store/q3sbhgbydsa56lflkr1k8hn49ha3wv63-master.tar.gz.drv
building '/nix/store/q3sbhgbydsa56lflkr1k8hn49ha3wv63-master.tar.gz.drv'...
unpacking channels...
created 2 symlinks in user environment
~ (10:45|7s) $ nix-env -iA twterm
error: attribute 'twterm' in selection path 'twterm' not found

~ (10:45|0s) $ nix-channel --add https://github.com/ryota-ka/twterm/archive/master.tar.gz
~ (10:46|0s) $ nix-channel --update                                                      
unpacking channels...
~ (10:46|1s) $ nix-env -iA twterm                                                        
error: attribute 'twterm' in selection path 'twterm' not found

```

**Comment by ryota-ka** [comment]
Thank you @mmngreco, I'll check it out later.

Whine Nix installation is recommended (as it also resolves and installs all the requirements such as the runtime and the dynamic libraries at the same time), twterm is also available via Homebrew tap.
If you are familiar with it and still having a trouble with Nix, please try using Homebrew.
Sorry for inconvenience.
